# Generated by Django 4.2.1 on 2023-06-05 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('poste', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='dateAchat',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 0, 3, 5, 298033)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dateFinContrantMaint',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 0, 3, 5, 298033)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 0, 3, 5, 298033)),
        ),
    ]
