# Generated by Django 4.2.1 on 2023-06-06 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0005_alter_machine_dateachat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='dateAchat',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 27, 39, 794510)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dateFinContrantMaint',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 27, 39, 794510)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 27, 39, 794510)),
        ),
        migrations.AlterField(
            model_name='maintenancepreventive',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 27, 39, 795508)),
        ),
        migrations.AlterField(
            model_name='utilisateurmachine',
            name='dateAttribution',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 27, 39, 795508)),
        ),
    ]
