# Generated by Django 4.2.1 on 2023-06-06 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0007_alter_machine_dateachat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='dateAchat',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 14, 52, 1, 724675)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dateFinContrantMaint',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 14, 52, 1, 724675)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 14, 52, 1, 724675)),
        ),
        migrations.AlterField(
            model_name='maintenancepreventive',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 14, 52, 1, 725670)),
        ),
        migrations.AlterField(
            model_name='utilisateurmachine',
            name='dateAttribution',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 14, 52, 1, 725670)),
        ),
    ]
